version: '3'
services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ux_glossary

  backend:
    build:
      context: ./backend
    container_name: ux-glossary-back
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - 5000:5000
    networks:
      - ux_glossary

  frontend:
    build:
      context: ./frontend
    container_name: ux-glossary-front
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 3000:3000
    networks:
      - ux_glossary
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000/api

networks:
  ux_glossary:
    driver: bridge

volumes:
  postgres_data:
