version: '3'
services:
  postgres:
    image: postgres
    restart: always
    env_file: 
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ux_glossary
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "2g"

  backend: 
    hostname: ux-glossary-back
    container_name: ux-glossary-back
    build: 
      context: ./
    restart: unless-stopped
    depends_on:
      - postgres
    env_file: 
      - .env
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - 5000:5000
    networks:
      - ux_glossary

networks:
  ux_glossary: 
    driver: bridge

volumes: 
  ux_glossary:
  postgres_data: